name: CI-Markdown

on:
  workflow_dispatch:
  pull_request:
  schedule:
    - cron: '0 8 * * *' # Nightly at 1am PST

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Spell check
        uses: streetsidesoftware/cspell-action@v6
        with:
          files: '**/*'
          config: '.vscode/cspell.json'
          strict: false
          suggestions: true
          incremental_files_only: true

      - name: Link check
        continue-on-error: true
        run: |
          npm install -g @umbrelladocs/linkspector
          linkspector check -c ./.github/.linkspector.yml
